# 1.Import the numpy package under the name np and Print the numpy version and the configuration .




In [ ]:
import numpy as np
print(np.__version__)#  it gives numpy version.
np.show_config() # it gives numpy configuration.


1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


# 2. Create a null vector of size 10






In [ ]:
import numpy as np
x = np.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]



#3. How to find number of dimensions, bytes per element and bytes of memory used?


In [ ]:
a=np.array([1,3,5,7.9])
print(a)
print(type(a))
print(a.dtype)

[1.  3.  5.  7.9]
<class 'numpy.ndarray'>
float64


# 4.How to find number of dimensions, bytes per element and bytes of memory used?









In [ ]:
x=np.array([1,3,5,7.9])
print(x)
print(x.ndim) # dimension 
print(x.itemsize)# bytes per element
print(x.size * x.itemsize)# bytes of memory used

[1.  3.  5.  7.9]
1
8
32


# 5.create a null vector of size 10 but the fifth value which is 1





In [ ]:
import numpy as np
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 6.Create a vector with values ranging from 10 to 49


In [ ]:
import numpy as np
x = np.arange(10,49)
print(x)
print("All the values except first and last vector :")
(x[1:-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
All the values except first and last vector :


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47])

#7. Reverse a vector (first element becomes last)


In [ ]:
import numpy as np
x=np.arange(5,20)
print("orginal array: ")
print(x)
print("Reverse array: ")
x=x[::-1]
print(x)

orginal array: 
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse array: 
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]


# 8.Create a 3x3 matrix with values ranging from 0 to 8


In [ ]:
import numpy as np
x=np.arange(0,8) 
print("original array")
print(x)
print(np.indices((3,3)))# 3 rows 3 columns

original array
[0 1 2 3 4 5 6 7]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


# 9.Find indices of non-zero elements from [1,2,0,0,4,0]


In [ ]:
x=[1,2,0,0,4,0]
print(x)
print(np.nonzero(x))

[1, 2, 0, 0, 4, 0]
(array([0, 1, 4]),)


#10. Create a 3x3 identity matrix


In [ ]:
array_2D=np.identity(3)
print("3*3 matrix: ")
print(array_2D)

3*3 matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 11. Create a 3x3x3 array with random values


In [ ]:
x= np.random.random((3,3,3))
print(x)

[[[0.08140456 0.54401629 0.69251135]
  [0.59362686 0.44129548 0.53546663]
  [0.83287838 0.93334019 0.01647548]]

 [[0.2526659  0.26369411 0.73569904]
  [0.7193199  0.69040208 0.05637042]
  [0.71638058 0.18976356 0.52663779]]

 [[0.88984691 0.37066023 0.69805697]
  [0.68828818 0.4225706  0.35312268]
  [0.38910003 0.60481116 0.743076  ]]]


# 12.Create a 10x10 array with random values and find the minimum and maximum values


In [ ]:
x=np.random.random((10,10))
print("original array :")
print(x)
xmin , xmax =x.min(),x.max()
print(" minimum and maximum :")
print(xmin , xmax)



original array :
[[0.55790082 0.35829239 0.81853685 0.46472098 0.64493518 0.32244194
  0.47631771 0.91534616 0.92507056 0.44643618]
 [0.53544138 0.06202009 0.43432126 0.83082583 0.09917885 0.72538558
  0.92994407 0.87334613 0.51746066 0.7498922 ]
 [0.7363508  0.53767955 0.08814397 0.60076346 0.42457579 0.60155683
  0.64414767 0.31655746 0.78284187 0.9614343 ]
 [0.89689678 0.45035834 0.88641897 0.97102701 0.10848963 0.88525075
  0.37639555 0.62274584 0.89430303 0.54499914]
 [0.03705625 0.8911453  0.69204416 0.477496   0.35241919 0.64857284
  0.14237665 0.232149   0.4464831  0.4844256 ]
 [0.43145713 0.7927086  0.83137798 0.95896922 0.6469213  0.33141933
  0.81809618 0.55956732 0.472218   0.75053425]
 [0.00587482 0.35159386 0.44487326 0.50435835 0.61351757 0.51649532
  0.10838635 0.15002209 0.5092313  0.36919708]
 [0.66267409 0.18277937 0.97603148 0.96071296 0.33428765 0.37638987
  0.49997628 0.75831557 0.54639176 0.70272081]
 [0.86638736 0.1424572  0.12693021 0.4788505  0.04649134 0.8536

#13. Create a random vector of size 30 and find the mean value


In [ ]:
x=np.random.random(10)
m=x.mean()
print(m)


0.4308320385120944


#14.Create a 2d array with 1 on the border and 0 inside.


In [ ]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#15.How to add a border (filled with 0's) around an existing array? 


In [ ]:
x=np.ones((5,5))
print(x)
print(" o's on the border :")
x=np.pad(x, pad_width=1 , mode='constant',constant_values=0)
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 o's on the border :
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?
#Example -
#[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

#Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20





In [ ]:
x=np.array([[ 1 ,2 ,3, 4, 5, 6, 7],[ 8, 9, 10, 11, 12, 13, 14]])
print("get 13 :",x[1,5])
print("get first row:",x[0])
print("get 3rd column:",x[:2])
print("get[2,4,6]=",[x[0,1],x[0,3],x[0,5]])
x[1,5]= 20
print("Replaced 13 by 20 ",x)

get 13 : 13
get first row: [1 2 3 4 5 6 7]
get 3rd column: [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
get[2,4,6]= [2, 4, 6]
Replaced 13 by 20  [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


#17.How to Convert a 1D array to a 2D array with 2 rows.



In [ ]:
x=np.arange(9)
print(x)
x= np.reshape(x,(3,3))
print(x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

#input: a = np.array([1,2,3])`
# Desired output: #array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [ ]:
x=np.array([1,2,3])
np.r_[np.repeat(x,3),np.tile(x,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 19. Write a program to show how Numpy taking less memory compared to Python List?



In [ ]:
import numpy as np
l=range(1000)
import sys
a=10
print("numpy_memory:",sys.getsizeof(a))         
print("list_memory:", sys.getsizeof(a)*len(l))  

numpy_memory: 28
list_memory: 28000


#20.Write a program to show how Numpy taking less time compared to Python List?



In [ ]:
import numpy
import time
size = 1000000  # size of arrays and lists
l1 = range(size)# declaring lists
l2 = range(size)
 
array_1 = numpy.arange(size) # declaring arrays
array_2 = numpy.arange(size)
S_Time = time.time()
r = [(a * b) for a, b in zip(l1, l2)] 
print("Time taken by Lists :",(time.time() - initialTime),"seconds")
initialTime = time.time()
r = array_1 *  array_2
print("Time taken by NumPy Arrays :",(time.time() - initialTime),"seconds")

Time taken by Lists : 50.29423689842224 seconds
Time taken by NumPy Arrays : 0.017818212509155273 seconds
